In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("Downloads/bank.csv")

In [3]:
dataset.head(10)

age         job   marital  education default  balance housing loan  \
0   59      admin.   married  secondary      no     2343     yes   no   
1   56      admin.   married  secondary      no       45      no   no   
2   41  technician   married  secondary      no     1270     yes   no   
3   55    services   married  secondary      no     2476     yes   no   
4   54      admin.   married   tertiary      no      184      no   no   
5   42  management    single   tertiary      no        0     yes  yes   
6   56  management   married   tertiary      no      830     yes  yes   
7   60     retired  divorced  secondary      no      545     yes   no   
8   37  technician   married  secondary      no        1     yes   no   
9   28    services    single  secondary      no     5090     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may      1042         1     -1         0  unknown     yes  
1  unknown    5   may      1467         1     -1         0  unknown     yes  
2  unknown    5   may      1389         1     -1         0  unknown     yes  
3  unknown    5   may       579         1     -1         0  unknown     yes  
4  unknown    5   may       673         2     -1         0  unknown     yes  
5  unknown    5   may       562         2     -1         0  unknown     yes  
6  unknown    6   may      1201         1     -1         0  unknown     yes  
7  unknown    6   may      1030         1     -1         0  unknown     yes  
8  unknown    6   may       608         1     -1         0  unknown     yes  
9  unknown    6   may      1297         3     -1         0  unknown     yes

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [6]:
x = dataset.iloc[:, 0:16].values
y = dataset.iloc[:, 16:17].values

In [7]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [8]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [9]:
x.shape

(11162, 16)

In [10]:
y.shape

(11162, 1)

In [11]:
#converting all textual data i.e. job, marital, education, default, housing, loan, contact, month, poutcome to binary

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [12]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder = "passthrough")
x = ct.fit_transform(x)

In [13]:
x.shape

(11162, 51)

In [14]:
ct1 = ColumnTransformer([("one",OneHotEncoder(),[0])],remainder = "passthrough")
y = ct1.fit_transform(y)

In [15]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [16]:
y.shape

(11162, 2)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2,random_state = 0)

In [18]:
print('x shape ', x.shape)
print('y shape ', y.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

x shape  (11162, 51)
y shape  (11162, 2)
x_train shape  (8929, 51)
x_test shape  (2233, 51)
y_train shape  (8929, 2)
y_test shape (2233, 2)


In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [20]:
x_train[0:2,:]

array([[-0.37172192, -0.45760242, -0.17658264, -0.1589378 ,  1.8452729 ,
        -0.27363591, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772, -0.36485864,  0.86351031, -0.66975544,
        -0.39346051,  1.01614555, -0.69993206, -0.21741017,  0.12621015,
        -0.12621015, -1.05825117,  1.05825117,  0.39003722, -0.39003722,
        -1.60273048, -0.27292594,  1.93439945, -0.30193478, -0.39913565,
        -0.09686471, -0.27410848, -0.17488949, -0.39459853, -0.34910544,
        -0.15930776,  1.70870313, -0.30215554, -0.1931085 , -0.16761389,
        -0.35031555, -0.22657536, -0.32939951,  0.58661881,  0.64941897,
        -0.44565283, -0.90504798, -0.2483547 , -0.56394809, -0.48428507,
        -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, -0.1589378 , -0.54192526,
         3.65449114, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772,  2.7407875 , -1.15806377, -0.66975544,
        -0.39346051,  1.01614

In [21]:
x_train.shape

(8929, 51)

In [22]:
y_train.shape

(8929, 2)

In [23]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [24]:
classification = Sequential()

In [25]:
classification.add(Dense(units=51,kernel_initializer='random_uniform',activation='relu'))

In [27]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [28]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [29]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [30]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [34]:
classification.compile(optimizer = "adam",loss = "categorical_crossentropy",metrics = ["accuracy"])

In [36]:
classification.fit(x_train,y_train, epochs = 50)

Epoch 1/50
280/280 [==============================] - 0s 1ms/step - loss: 0.1111 - accuracy: 0.9554
Epoch 2/50
280/280 [==============================] - 0s 1ms/step - loss: 0.1051 - accuracy: 0.9578
Epoch 3/50
280/280 [==============================] - 0s 1ms/step - loss: 0.0999 - accuracy: 0.9589
Epoch 4/50
280/280 [==============================] - 0s 1ms/step - loss: 0.0918 - accuracy: 0.9644
Epoch 5/50
280/280 [==============================] - 0s 1ms/step - loss: 0.1040 - accuracy: 0.9577
Epoch 6/50
280/280 [==============================] - 0s 1ms/step - loss: 0.0937 - accuracy: 0.9634
Epoch 7/50
280/280 [==============================] - 0s 973us/step - loss: 0.0906 - accuracy: 0.9652
Epoch 8/50
280/280 [==============================] - 0s 998us/step - loss: 0.0955 - accuracy: 0.9621
Epoch 9/50
280/280 [==============================] - 0s 1ms/step - loss: 0.0801 - accuracy: 0.9693
Epoch 10/50
280/280 [==============================] - 0s 969us/step - loss: 0.0807 - accuracy: 

In [39]:
ypred = classification.predict(x_test)

In [38]:
ypred

array([[1.0000000e+00, 4.9253467e-15],
       [7.7220058e-01, 2.2779942e-01],
       [1.0000000e+00, 2.6006336e-19],
       ...,
       [4.2099820e-04, 9.9957901e-01],
       [1.0000000e+00, 1.3711653e-14],
       [1.0000000e+00, 4.2375735e-11]], dtype=float32)

In [40]:
ypred=ypred>0.5

In [41]:
y_test

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [42]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [54]:
deposit=["No","Yes"]
yp=classification.predict(sc.transform(ct.transform([[59,'admin.','married','secondary','no',2343,'yes','no','unknown',5,'may',1042,1,-1,0,'unknown']])))
prediction=deposit[np.argmax(yp)]


In [55]:
prediction

'Yes'